# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSuyNJF2lvLoPmk_IAFr2xkzR03Io2Ly
"""

pip install beautifulsoup4            # beautifulsoup installing

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer     # Vader package

import requests
import re
from bs4 import BeautifulSoup           # beautifulsoup package

nltk.download('vader_lexicon')
sentiment = SentimentIntensityAnalyzer()    # vader object

def getStockScore(stockName, pageScope):
  resultList = []
  dateList = []
  scoreList = []

  for i in range(1, int(pageScope) + 1):
    # 링크 url 설정
    url = 'https://www.investing.com/equities/' + str(stockName) + '-news/' + str(i)

    # html 추출
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    # 날짜 추출
    dates = soup.find_all('time', 'ml-2')
    for d in dates:
      dateList.append(d.string)

    # 개별 뉴스 링크 추출
    linkList = []
    links = soup.find_all('a', attrs={'data-test': 'article-title-link'})
    for link in links:
      href = link.attrs['href']
      linkList.append('https://www.investing.com/' + href)

    # 뉴스 점수 추출
    for a in linkList:
      response_a = requests.get(a)
      soup_a = BeautifulSoup(response_a.text, 'html.parser')
      text_div = soup_a.select('#leftColumn > div.WYSIWYG.articlePage > p')
      text = ''
      for t in text_div: 
        text += t.get_text()
      scoreList.append(sentiment.polarity_scores(text)['compound'])
    
  for i in range(len(dateList)):
    resultList.append([dateList[i], scoreList[i]])

  return resultList

'''
link = 'https://www.investing.com/equities/'
usStable = ['coca-cola-co', 'mcdonalds', 'waste-managemnt', 'republic-services-inc', 'pepsico', 'colgate-palmo', 'wal-mart-stores', 'cboe-holdings-inc', 'general-dynam', 'kimberly-clark', 'procter-gamble', 'amerisourcebergn']
usUnstable = ['apple-computer-inc', 'microsoft-corp', 'amazon-com-inc', 'nvidia-corp', 'facebook-inc', 'avago-technologies', 'google-inc', 'tesla-motors', 'adobe-sys-inc', 'costco-whsl-corp-new', 'cisco-sys-inc', 'netflix,-inc.', 'adv-micro-device']
korStable = ['samsung-electronics-co-ltd', ]
korUnstable = []
'''